name: Run Selenium Tests
on:
  push:
    branches: [main]
jobs:
  Run:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Add VSTest.console.exe to the PATH
      uses: darenm/Setup-VSTest@v1
      
    - name: Change directory
      run: cd ".."

    - name: Run test command
      run: |
        cd "..\..\unit-tests\unit-tests"
        dir
        vstest.console.exe "SeleniumCSharp\bin\Debug\net8.0\AppealsTests.dll"
      
