name: Run Selenium Tests
on:
  push:
    branches: [main]
jobs:
  Run:
    runs-on: windows-latest
    steps:
    - name: Add VSTest.console.exe to the PATH
      uses: darenm/Setup-VSTest@v1
      
    - name: Run test command
      run: vstest.console.exe "..\..\SeleniumCSharp\bin\Debug\net8.0\AppealsTests.dll"
      
